
/////////////////////////////////////////////////////////
// some stuff

static const char* const image0_data[] = { 
"32 32 24 1",
". c #020202",
"d c #0c0c0c",
"g c #141414",
"r c #1a1a1a",
"s c #222222",
"j c #2b2b2b",
"i c #343434",
"q c #3e3e3e",
"t c #505050",
"# c #525252",
"v c #5b5b5b",
"e c #656565",
"f c #6c6c6c",
"k c #747474",
"n c #7c7c7c",
"p c #848484",
"m c #8c8c8c",
"h c #949494",
"l c #9c9c9c",
"u c #a4a4a4",
"c c #acacac",
"o c #b4b4b4",
"b c #bcbcbc",
"a c #c4c4c4",
"................................",
".......###############..........",
"..#####abbbbbbc#bbbbba###.......",
".#abbbbbbbbbba.abbbbbbbba##.....",
"###abbbbbbbbadcbbbbbbbbbbbb#....",
"...##e#bbbbbfgbbbbbbbbbbbbbb#...",
".......#bbba.cbbbbbbbbbbbbbbb#..",
".....####hbi.abbbbbbbbbbbbbbbb#.",
"...##aababa.jbbbbbbbbbbbbbbbbb#.",
"...##abbbb#.gabbbbbbbbbbbbbbbbb#",
".....##bba...kbbbbbbbbbbbbbbbbb#",
".......##b....lbbbbbamfnoabbbbb#",
"......##lm....dbbbbk......hbbbb#",
".....#aaab.....abbb........#bag#",
"......#obb....gbbbb.........af.d",
".......#bb....pbbbbq........aq.r",
"........#br..sabbbbbn......fbo.#",
".........#btmbbbbbbbbaufvpabbba#",
".........#bbbbbbbbbbbbbbbbbbbbb#",
"..........#bbbbbbbbbbbbbbbbbbbb#",
"..........#bbbbbbbbbbbbbbbbbbbo#",
"..........#bbbbbbbbbbbbbbbbbbb#.",
"...........#bbbbbbbbbbbbbbbbbb#.",
"...........#bbbbbbbbbbbbbbbbb#..",
"............#bbbbbbbbbbbbbbbb#..",
".............##bbbbbbbbbbbbb#...",
"...............#bbbbbbbbbbbb#...",
"................##bbbbbbbbb#....",
"..................###abbbb#.....",
".....................#####......",
"................................",
"................................"};
