/* openlibraries_global_config.hpp.  Generated by configure.  */
/* openlibraries_global_config.hpp.in.  Generated from configure.ac by autoheader.  */

/* Define this if you have Boost filesystem support */
#define HAVE_BOOST_FILESYSTEM 1

/* Define this if you have bzip2 support */
#define HAVE_BZIP2 1

/* Define this if you have NVIDIA Cg runtime support */
/* #undef HAVE_CG_RUNTIME */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define this to enable fast math support */
#define HAVE_FAST_MATH 1

/* Define this if you have GLEW support */
#define HAVE_GL_GLEW_H 1

/* Define this if you have GLUT support */
/* #undef HAVE_GL_GLUT_H */

/* Define this if you have GLU support */
#define HAVE_GL_GLU_H 1

/* Define this if you have OpenGL support */
#define HAVE_GL_GL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define this if you have libavformat */
/* #undef HAVE_LIBAVFORMAT */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define this for mlt support */
/* #undef HAVE_LIBMLT */

/* Define this for PNG support */
#define HAVE_LIBPNG 1

/* Define this for sdl support */
/* #undef HAVE_LIBSDL */

/* Define this for libxml2 support */
#define HAVE_LIBXML2 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define this if you have OFX support */
/* #undef HAVE_OFX */

/* Define this if you have Creative OpenAL runtime support */
/* #undef HAVE_OPENAL */

/* Define this to use Creative OpenAL framework (OSX only) */
/* #undef HAVE_OPENALFRAMEWORK */

/* Defined if you have openassetlib */
#define HAVE_OPENASSETLIB 1

/* Defined if you have openeffectlib */
#define HAVE_OPENEFFECTLIB 1

/* Define this if you have ILM OpenEXR */
#define HAVE_OPENEXR 1

/* Define this for OpenImageLib support */
#define HAVE_OPENIMAGELIB 1

/* Defined if you have openobjectlib */
#define HAVE_OPENOBJECTLIB 1

/* Define this if you want memory pooling */
#define HAVE_POOLING 1

/* Define this if you have Python support */
#define HAVE_PYTHON 1

/* Define this if you have Qt runtime support */
#define HAVE_QT 1

/* Define this if you have QuickTime support */
/* #undef HAVE_QUICKTIME */

/* Define this if you have SQLite support */
#define HAVE_SQLITE3 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define this if you have TIFF support */
#define HAVE_TIFF_H 1

/* Define this if you want a umbrella framework */
/* #undef HAVE_UMBRELLAFRAMEWORK */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define this if you have X11R6 installed */
#define HAVE_X11 1

/* Define this if you have zlib support */
#define HAVE_ZLIB 1

/* Name of package */
#define PACKAGE "openlibraries"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.5.0"

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */
