
// fx - A compositing library representation.

// Copyright (C) 2005-2006 VM Inc.
// Released under the LGPL.
// For more information, see http://www.openlibraries.org.

float4 main( in float2 v_tex, uniform float min, uniform float max, uniform float4 channels, uniform samplerRECT inColor0 ) : COLOR
{
	float4 color = texRECT( inColor0, v_tex );
	
	float level = clamp( dot( channels, color ), 0.0f, 1.0f );
	if( level < min || level >= max )
		discard;

	return color;
}
