
half4 main(
	float2 position           				: TEXCOORD1,
	uniform float horizontal 				: register (c0),
	uniform float vertical 					: register (c1),
    uniform sampler2D texture				: register (s0)
		   ) : COLOR
{
	float4 					Color;
	float2					new_position;

	new_position.x = position.x + horizontal;
	new_position.y = position.y + vertical;
	
	Color = (half4)tex2D(texture, new_position);

    return (half4)Color;
}
